export {
  UPGRADE_CHANGE_TYPES,
  UPGRADE_CATALOG_GROUPS,
  CHANGE_TYPES,
  getTemplateByKey,
  UPGRADE_TEMPLATES,
  isAllowedUpgradeType,
  isAllowedChangeType,
  isUpgradeType,
  type ChangeType,
  type UpgradeCatalogEntry,
  type UpgradeCatalogGroup,
  type UpgradeTemplate,
  type FieldDescriptor,
} from "@/modules/upgradesLedger/catalog";
