import { readFileSync } from "fs";
import { resolve } from "path";
import { describe, expect, it } from "vitest";

const ROOT = process.cwd();

function readRepoFile(relativePath: string): string {
  return readFileSync(resolve(ROOT, relativePath), "utf8");
}

describe("One Path Sim Admin harness wiring", () => {
  it("adds the admin harness page and tool navigation entry", () => {
    const pageSource = readRepoFile("app/admin/tools/one-path-sim/page.tsx");
    const toolsGridSource = readRepoFile("components/admin/AdminToolsGrid.tsx");
    const adminPageSource = readRepoFile("app/admin/page.tsx");

    expect(pageSource).toContain("OnePathSimAdmin");
    expect(toolsGridSource).toContain('/admin/tools/one-path-sim');
    expect(toolsGridSource).toContain("One Path Sim Admin");
    expect(adminPageSource).toContain('/admin/tools/one-path-sim');
  });

  it("keeps the harness thin and reuses shared editors", () => {
    const source = readRepoFile("components/admin/OnePathSimAdmin.tsx");
    const policySource = readRepoFile("modules/usageSimulator/simulationVariablePolicy.ts");

    expect(source).toContain("Home Details popup/editor");
    expect(source).toContain("Appliance Details popup/editor");
    expect(source).toContain("Travel/Vacant Dates popup/editor");
    expect(source).toContain("Manual Usage Entry popup/editor");
    expect(source).toContain("HomeDetailsClient");
    expect(source).toContain("AppliancesClient");
    expect(source).toContain("ManualUsageEntry");
    expect(source).toContain('fetch("/api/admin/tools/one-path-sim"');
    expect(source).toContain("render from the shared read model only");
    expect(source).toContain("pre-cutover canonical simulation truth console");
    expect(source).toContain("Older surfaces are not rerouted to this harness yet.");
    expect(source).toContain("VALIDATION_SELECTION_OPTIONS");
    expect(source).toContain("Actual context house");
    expect(source).toContain("Manual validation date keys");
    expect(source).toContain("Known-house scenario preset");
    expect(source).toContain("Brian sandbox house is the default tuning context");
    expect(source).toContain('useState(DEFAULT_BRIAN_KNOWN_SCENARIO_KEY)');
    expect(source).toContain("Load known scenario preset");
    expect(source).toContain("Chart / Window / Display Logic");
    expect(source).toContain("Manual Statement / Annual Logic");
    expect(source).toContain("Shared source-of-truth summary");
    expect(source).toContain("Stage Boundary Map");
    expect(source).toContain("Upstream Usage Truth");
    expect(source).toContain("Shared Derived Inputs Used By Run");
    expect(source).toContain("Source Truth / Compare Truth Identity");
    expect(source).toContain("Constraint / Rebalance Logic");
    expect(source).toContain("Donor / Fallback / Exclusion Logic");
    expect(source).toContain("Intraday Reconstruction Logic");
    expect(source).toContain("Final Shared Output Contract");
    expect(source).toContain("Annual Shared Truth");
    expect(source).toContain("New Build Shared Truth");
    expect(source).toContain("Editable Shared Config / Inputs");
    expect(source).toContain("Read-Only Shared Run Truth");
    expect(source).toContain("One Path Hard Audit");
    expect(source).toContain("One Path surface audit matrix");
    expect(source).toContain("AI copy payload inventory");
    expect(source).toContain("Shared wiring flow");
    expect(source).toContain("External surface classification");
    expect(source).toContain("Drift-risk watchlist");
    expect(source).toContain("runResult.readModel?.sourceOfTruthSummary?.stageBoundaryMap");
    expect(source).toContain("runResult?.readModel?.sourceOfTruthSummary?.upstreamUsageTruth");
    expect(source).toContain("runResult.readModel?.sourceOfTruthSummary?.sharedDerivedInputs");
    expect(source).toContain("runResult.readModel?.sourceOfTruthSummary?.sourceTruthIdentity");
    expect(source).toContain("runResult.readModel?.sourceOfTruthSummary?.constraintRebalance");
    expect(source).toContain("runResult.readModel?.sourceOfTruthSummary?.donorFallbackExclusions");
    expect(source).toContain("runResult.readModel?.sourceOfTruthSummary?.intradayReconstruction");
    expect(source).toContain("runResult.readModel?.sourceOfTruthSummary?.finalSharedOutputContract");
    expect(source).not.toContain("resolveCanonicalUsage365CoverageWindow(");
    expect(source).not.toContain("resolveManualStageOnePresentation(");
    expect(source).not.toContain("buildManualBillPeriodTargets(");
    expect(source).not.toContain("resolveSharedWeatherSensitivityEnvelope(");
    expect(source).toContain('value: "random_simple"');
    expect(source).toContain('value: "customer_style_seasonal_mix"');
    expect(source).toContain('value: "stratified_weather_balanced"');
    expect(source).toContain('useState("stratified_weather_balanced")');
    expect(source).toContain("Validation mode popup");
    expect(source).toContain("VALIDATION_SELECTION_MODE_DETAILS");
    expect(source).toContain("Current admin adjustments");
    expect(source).toContain("Use this mode");
    expect(source).toContain("shared selector path");
    expect(source).toContain("<select");
    expect(source).toContain("sourceContext?.travelRangesFromDb");
    expect(source).toContain("lookup?.sourceContext?.upstreamUsageTruth");
    expect(source).toContain("Shared calculation variable popups");
    expect(source).toContain("buildOnePathSandboxHarnessSummary");
    expect(source).toContain("getKnownHouseScenarioByKey");
    expect(source).toContain("KNOWN_HOUSE_SCENARIOS");
    expect(source).toContain("resolveKnownHouseScenarioSelection");
    expect(source).toContain("sandboxHarnessSummary");
    expect(source).toContain("openVariableFamily");
    expect(source).toContain("Copy all variables for AI");
    expect(source).toContain("Copy this family for AI");
    expect(source).toContain("readModel: (runResult?.readModel");
    expect(source).toContain("artifact: (runResult?.artifact");
    expect(source).toContain("Resolved value used by sim");
    expect(source).toContain("Adjust this value");
    expect(source).toContain("Raw code / JSON editor");
    expect(source).toContain("OVERRIDE field");
    expect(source).toContain('fetch("/api/admin/tools/one-path-sim/variables"');
    expect(source).toContain("Save shared override");
    expect(policySource).toContain("Adapter / Canonical Input");
    expect(policySource).toContain("Constraint / Rebalance");
    expect(policySource).toContain("Donor / Fallback / Exclusions");
    expect(policySource).toContain("Intraday Shape Reconstruction");
    expect(policySource).toContain("Compare / Tuning Metrics");
    expect(source).toContain("Effective Variables Used By Last Run");
    expect(source).toContain("Sandbox run status");
    expect(source).toContain("Monthly truth / compare snapshot");
    expect(source).toContain("Weather / daily-shape snapshot");
    expect(source).toContain("Interval / compare visibility snapshot");
    expect(source).toContain("Baseline parity audit");
    expect(source).toContain("Household energy insights");
    expect(source).toContain("Monthly usage");
    expect(source).toContain("Daily usage");
    expect(source).toContain("15-minute load curve");
    expect(source).toContain("OnePathBaselineReadOnlyView");
    expect(source).toContain("Known scenario / expectations");
    expect(source).toContain("Tuning cycle summary");
    expect(source).toContain("runResult.readModel?.effectiveSimulationVariablesUsed");
    expect(source).toContain("explicit admin override");
    const presentationSource = readRepoFile("modules/onePathSim/simulationVariablePresentation.ts");
    const isolatedPresentationEntrySource = readRepoFile("modules/onePathSim/simulationVariablePresentation.ts");
    const adminHarnessSummarySource = readRepoFile("modules/onePathSim/adminHarnessSummary.ts");
    const knownScenarioSource = readRepoFile("modules/onePathSim/knownHouseScenarios.ts");
    const knownScenarioPrereqSource = readRepoFile("modules/onePathSim/knownHouseScenarioPrereqs.ts");
    expect(presentationSource).toContain("curveShapingSummary");
    expect(presentationSource).toContain("upstreamUsageTruth");
    expect(presentationSource).toContain("Highest-priority shape-sensitive shared variables first");
    expect(isolatedPresentationEntrySource).toContain("buildSimulationVariableCopyPayload");
    const truthSummarySource = readRepoFile("modules/onePathSim/onePathTruthSummary.ts");
    const isolatedTruthSummaryEntrySource = readRepoFile("modules/onePathSim/onePathTruthSummary.ts");
    expect(truthSummarySource).toContain("resolveCanonicalUsage365CoverageWindow");
    expect(truthSummarySource).toContain("projectBaselineFromCanonicalDataset");
    expect(truthSummarySource).toContain("resolveManualStageOnePresentation");
    expect(truthSummarySource).toContain("buildManualBillPeriodTargets");
    expect(truthSummarySource).toContain("stageBoundaryMap");
    expect(truthSummarySource).toContain("upstreamUsageTruth");
    expect(truthSummarySource).toContain("sharedDerivedInputs");
    expect(truthSummarySource).toContain("sourceTruthIdentity");
    expect(truthSummarySource).toContain("constraintRebalance");
    expect(truthSummarySource).toContain("donorFallbackExclusions");
    expect(truthSummarySource).toContain("intradayReconstruction");
    expect(truthSummarySource).toContain("finalSharedOutputContract");
    expect(truthSummarySource).toContain("annualModeTruth");
    expect(truthSummarySource).toContain("newBuildModeTruth");
    expect(isolatedTruthSummaryEntrySource).toContain("buildOnePathTruthSummary");
    expect(adminHarnessSummarySource).toContain("buildOnePathSandboxHarnessSummary");
    expect(adminHarnessSummarySource).toContain("compareProjectionMetrics");
    expect(adminHarnessSummarySource).toContain("weatherEfficiencyDerivedInput");
    expect(adminHarnessSummarySource).toContain("curveCompareActualIntervals15");
    expect(adminHarnessSummarySource).toContain("manualMonthlyReconciliation");
    const tuningCycleSummarySource = readRepoFile("modules/onePathSim/tuningCycleSummary.ts");
    expect(knownScenarioSource).toContain("KNOWN_HOUSE_SCENARIOS");
    expect(knownScenarioSource).toContain("PRIMARY_BRIAN_SANDBOX_CONTEXT");
    expect(knownScenarioSource).toContain("DEFAULT_BRIAN_KNOWN_SCENARIO_KEY");
    expect(knownScenarioSource).toContain("resolveKnownHouseScenarioSelection");
    expect(knownScenarioSource).toContain("matchScenarioIdByHint");
    expect(knownScenarioSource).toContain("scenarioKey");
    expect(source).toContain("orderedKnownScenarios");
    expect(source).toContain("Known scenario prerequisite status");
    expect(source).toContain("buildKnownHouseScenarioPrereqStatus");
    expect(knownScenarioPrereqSource).toContain("buildKnownHouseScenarioPrereqStatus");
    expect(knownScenarioPrereqSource).toContain("homeDetailsReady");
    expect(knownScenarioPrereqSource).toContain("compareCapableNow");
    expect(knownScenarioPrereqSource).toContain("blockingReasons");
    expect(presentationSource).toContain("knownScenario");
    expect(presentationSource).toContain("sandboxSummary");
    expect(presentationSource).toContain("tuningCycleSummary");
    expect(source).toContain("buildOnePathTuningCycleSummary");
    expect(tuningCycleSummarySource).toContain("buildOnePathTuningCycleSummary");
    expect(tuningCycleSummarySource).toContain("biggestDriftReason");
    expect(tuningCycleSummarySource).toContain("thresholdStatus");
    const ownershipAuditSource = readRepoFile("modules/onePathSim/onePathOwnershipAudit.ts");
    const isolatedOwnershipAuditEntrySource = readRepoFile("modules/onePathSim/onePathOwnershipAudit.ts");
    expect(ownershipAuditSource).toContain("buildOnePathOwnershipAudit");
    expect(ownershipAuditSource).toContain("pageSurfaceAuditMatrix");
    expect(isolatedOwnershipAuditEntrySource).toContain("sharedWiringFlow");
  });
});
