/** Phase 3A compatibility facade — canonical owner: modules/manualUsage/statementRanges.ts */
export {
  MAX_MANUAL_MONTHLY_BILLS,
  addDaysToIsoDate,
  buildContiguousStatementRanges,
  buildManualAnnualStageOneSummary,
  buildManualBillPeriodTargets,
  buildManualBillPeriodTotalsById,
  buildManualMonthlyStageOneRows,
  buildMonthlyPayloadFromStatementRows,
  buildStatementRowsFromMonthlyPayload,
  deriveStatementRangesFromMonthlyPayload,
  formatStatementRangeLabel,
  normalizeStatementRanges,
  normalizeTravelRanges,
  pickManualUsagePayload,
  pickMonthlyManualUsagePayload,
  resolveManualAnnualStageOnePresentation,
  resolveManualMonthlyLabStageOnePayloads,
  resolveManualMonthlyStageOnePresentation,
  resolveManualMonthlyStageOneRenderMode,
  resolveManualStageOneLabPayloads,
  resolveManualStageOnePresentation,
  shouldUseManualMonthlyStageOnePayload,
} from "@/modules/manualUsage/statementRanges";

export type {
  ManualAnnualStageOneSummary,
  ManualBillPeriodInputKind,
  ManualBillPeriodTarget,
  ManualMonthlyStageOneRow,
  ManualMonthlyStageOneSurface,
  ManualStageOnePresentation,
  ManualStatementInputRow,
} from "@/modules/manualUsage/statementRanges";
