type PriorityBand =
  | "Hard Constraint"
  | "Reference Truth Pool"
  | "Primary Driver"
  | "Secondary Driver"
  | "Conditional Adjustment"
  | "Exclusion"
  | "Fallback"
  | "Not Used";

type LogicModeFamily = "actual_backed" | "manual_monthly" | "manual_annual" | "profile_only" | "other";

export type CalculationLogicInputGroup = {
  key: string;
  label: string;
  used: boolean;
  sourceOfTruth: string;
  role: string;
  priorityBand: PriorityBand;
  details: string[];
};

export type CalculationLogicLayer = {
  key: string;
  title: string;
  summary: string;
  variablesUsed: string[];
  preservedOrLocked: string[];
  simulatedOrDerived: string[];
  fallbackOrder: string[];
  modeSpecificRules: string[];
};

export type CalculationLogicPriorityItem = {
  label: string;
  priorityBand: PriorityBand;
  explanation: string;
};

export type CalculationLogicExclusionItem = {
  label: string;
  value: string;
  effect: string;
};

export type CalculationLogicTuningLever = {
  label: string;
  priorityBand: Exclude<PriorityBand, "Not Used">;
  explanation: string;
};

export type GapfillCalculationLogicSummary = {
  selectedMode: string;
  modeLabel: string;
  modeFamily: LogicModeFamily;
  modeOverview: string;
  stageOnePath: string;
  stageTwoPath: string;
  sharedProducerPathUsed: boolean;
  sourceHouseId: string | null;
  testHomeId: string | null;
  inputGroups: CalculationLogicInputGroup[];
  layers: CalculationLogicLayer[];
  priorityItems: CalculationLogicPriorityItem[];
  exclusions: CalculationLogicExclusionItem[];
  tuningLevers: CalculationLogicTuningLever[];
  rawDiagnostics: Record<string, unknown>;
};

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function asArray<T = unknown>(value: unknown): T[] {
  return Array.isArray(value) ? (value as T[]) : [];
}

function countBy<T>(items: T[], toKey: (item: T) => string | null | undefined): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const item of items) {
    const key = String(toKey(item) ?? "").trim();
    if (!key) continue;
    counts[key] = (counts[key] ?? 0) + 1;
  }
  return counts;
}

function joinNonEmpty(parts: Array<string | null | undefined>, sep = " | "): string {
  return parts.map((part) => String(part ?? "").trim()).filter(Boolean).join(sep);
}

function describeCountMap(counts: Record<string, number>, empty = "none observed"): string {
  const entries = Object.entries(counts).filter(([, value]) => Number(value) > 0);
  if (entries.length === 0) return empty;
  return entries
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 6)
    .map(([key, value]) => `${key}: ${value}`)
    .join(" | ");
}

function formatMaybeNumber(value: unknown, digits = 2): string {
  return typeof value === "number" && Number.isFinite(value) ? value.toFixed(digits) : "not attached";
}

function formatMaybeCount(value: unknown): string {
  return typeof value === "number" && Number.isFinite(value) ? String(value) : "not attached";
}

function inferModeInfo(selectedMode: string, lockboxMode: string): {
  modeFamily: LogicModeFamily;
  modeLabel: string;
  stageOnePath: string;
  modeOverview: string;
} {
  const key = String(selectedMode || lockboxMode).trim();
  switch (key) {
    case "EXACT_INTERVALS":
    case "ACTUAL_INTERVAL_BASELINE":
    case "actual_data_fingerprint":
      return {
        modeFamily: "actual_backed",
        modeLabel: "Exact Intervals / Actual-Backed",
        stageOnePath: "Use source actual intervals as the pre-normalization truth input. No manual totals are created.",
        modeOverview:
          "This run is actual-backed: trusted source intervals stay primary, exclusions trim the usable reference pool, and compare scores persisted modeled output against actual validation days.",
      };
    case "MONTHLY_FROM_SOURCE_INTERVALS":
    case "MANUAL_MONTHLY":
    case "manual_monthly_constrained":
      return {
        modeFamily: "manual_monthly",
        modeLabel: "Manual Monthly Constrained",
        stageOnePath:
          "Run the shared manual-monthly Stage 1 helper flow first: source payload precedence, seeded statement ranges when needed, then monthly totals enter the lockbox as hard constraints.",
        modeOverview:
          "This run uses manual monthly constrained input: monthly totals stay fixed, bill-range semantics remain relevant for reconciliation, and daily/interval detail is generated by the shared Past simulator.",
      };
    case "ANNUAL_FROM_SOURCE_INTERVALS":
    case "MANUAL_ANNUAL":
    case "manual_annual_constrained":
      return {
        modeFamily: "manual_annual",
        modeLabel: "Manual Annual Constrained",
        stageOnePath:
          "Run the shared manual-annual Stage 1 helper flow first: source payload precedence, annual seed selection when needed, then one annual total enters the lockbox as the hard constraint.",
        modeOverview:
          "This run uses manual annual constrained input: the annual total stays fixed, monthly distribution is derived, and daily/interval detail is generated by the shared Past simulator.",
      };
    case "PROFILE_ONLY_NEW_BUILD":
      return {
        modeFamily: "profile_only",
        modeLabel: "Profile-Only New Build",
        stageOnePath:
          "Skip source-interval truth and build the run from home/appliance priors plus shared weather/profile context before lockbox entry.",
        modeOverview:
          "This run is profile-driven: home and appliance inputs lead, shared weather still shapes the output, and interval truth from a source house does not anchor the monthly result.",
      };
    default:
      return {
        modeFamily: "other",
        modeLabel: key || "Unknown GapFill Mode",
        stageOnePath: "Read the selected mode from persisted lockbox metadata. No extra mode-specific explanation was attached.",
        modeOverview:
          "This view is read-only and artifact-backed. It explains the persisted lockbox path without creating a second simulation path.",
      };
  }
}

function monthlyLayerSummary(modeFamily: LogicModeFamily): {
  summary: string;
  preservedOrLocked: string[];
  simulatedOrDerived: string[];
  modeSpecificRules: string[];
} {
  switch (modeFamily) {
    case "manual_monthly":
      return {
        summary: "Monthly totals are fixed first, then the shared simulator distributes daily and interval detail underneath those monthly constraints.",
        preservedOrLocked: ["Entered or source-derived monthly totals", "Bill-range intent for later reconciliation"],
        simulatedOrDerived: ["Daily totals inside each constrained month", "Interval curves inside each simulated day"],
        modeSpecificRules: [
          "Statement/bill-range semantics stay attached to the run.",
          "Monthly-target construction diagnostics explain travel-aware normalization when attached.",
        ],
      };
    case "manual_annual":
      return {
        summary: "The annual total is fixed first, then the shared builder derives monthly targets before daily and interval shaping.",
        preservedOrLocked: ["Single annual total"],
        simulatedOrDerived: ["Monthly allocation", "Daily totals", "Interval curves"],
        modeSpecificRules: [
          "Month targets are derived from the annual constraint instead of monthly statement entries.",
          "Annual allocation still flows into the same shared Stage 2 producer path.",
        ],
      };
    case "actual_backed":
      return {
        summary: "Monthly totals are aggregated from source intervals; there is no manual total constraint layer ahead of daily/interval truth.",
        preservedOrLocked: ["Actual interval-derived energy"],
        simulatedOrDerived: ["Only modeled keep-ref/test outputs where the shared producer requires them"],
        modeSpecificRules: [
          "The actual-backed branch preserves source interval truth as the baseline input.",
        ],
      };
    case "profile_only":
      return {
        summary: "Monthly targets are estimated from home/appliance priors because no actual-backed or manual total constraint anchors the run.",
        preservedOrLocked: ["Profile-only priors"],
        simulatedOrDerived: ["Monthly totals", "Daily totals", "Interval shapes"],
        modeSpecificRules: [
          "This mode is synthetic-first and falls back to priors earlier than other GapFill modes.",
        ],
      };
    default:
      return {
        summary: "Monthly targeting uses the persisted shared build inputs for the selected mode.",
        preservedOrLocked: [],
        simulatedOrDerived: [],
        modeSpecificRules: [],
      };
  }
}

export function buildGapfillCalculationLogicSummary(args: {
  selectedMode: string | null | undefined;
  dataset: any;
  sharedDiagnostics: unknown;
  compareProjection?: { rows?: unknown; metrics?: unknown } | null;
  sourceHouseId?: string | null;
  testHomeId?: string | null;
}): GapfillCalculationLogicSummary {
  const dataset = args.dataset ?? {};
  const meta = asRecord(dataset?.meta);
  const sharedDiagnostics = asRecord(args.sharedDiagnostics);
  const identityContext = asRecord(sharedDiagnostics.identityContext);
  const sourceTruthContext = asRecord(sharedDiagnostics.sourceTruthContext);
  const lockboxExecutionSummary = asRecord(sharedDiagnostics.lockboxExecutionSummary);
  const projectionReadSummary = asRecord(sharedDiagnostics.projectionReadSummary);
  const tuningSummary = asRecord(sharedDiagnostics.tuningSummary);
  const lockboxInput = asRecord(meta.lockboxInput);
  const perRunTrace = asRecord(meta.lockboxPerRunTrace);
  const sourceContext = asRecord(lockboxInput.sourceContext);
  const profileContext = asRecord(lockboxInput.profileContext);
  const validationKeys = asRecord(lockboxInput.validationKeys);
  const travelRanges = asRecord(lockboxInput.travelRanges);
  const perDayTrace = asArray<Record<string, unknown>>(meta.lockboxPerDayTrace);
  const compareProjection = asRecord(args.compareProjection);
  const compareMetrics = asRecord(compareProjection.metrics);
  const compareRows = asArray(compareProjection.rows);
  const selectedMode = String(
    args.selectedMode ??
      identityContext.usageInputMode ??
      lockboxInput.mode ??
      identityContext.simulatorMode ??
      ""
  ).trim();
  const lockboxMode = String(lockboxInput.mode ?? identityContext.simulatorMode ?? "").trim();
  const modeInfo = inferModeInfo(selectedMode, lockboxMode);
  const sharedProducerPathUsed = lockboxExecutionSummary.sharedProducerPathUsed === true || meta.sharedProducerPathUsed === true;
  const sourceHouseId =
    String(
      args.sourceHouseId ??
        identityContext.sourceHouseId ??
        sourceContext.sourceHouseId ??
        perRunTrace.sourceHouseId ??
        ""
    ).trim() || null;
  const testHomeId =
    String(
      args.testHomeId ??
        identityContext.profileHouseId ??
        profileContext.testHomeId ??
        perRunTrace.testHomeId ??
        profileContext.profileHouseId ??
        ""
    ).trim() || null;
  const travelRangeList = asArray<Record<string, unknown>>(travelRanges.ranges ?? sourceTruthContext.travelRangesUsed);
  const validationKeyList = asArray<string>(validationKeys.localDateKeys ?? sourceTruthContext.validationTestKeysUsed);
  const monthlyDiagnostics = asArray<Record<string, unknown>>(sourceTruthContext.monthlyTargetConstructionDiagnostics);
  const fingerprintDiagnostics = asRecord(sourceTruthContext.intervalUsageFingerprintDiagnostics);
  const perDayReasonCounts = countBy(perDayTrace, (row) => String(row.simulatedReasonCode ?? "").trim());
  const perDayFallbackCounts = countBy(perDayTrace, (row) => String(row.fallbackLevel ?? "").trim());
  const perDayShapeVariantCounts = countBy(perDayTrace, (row) => String(row.shapeVariantUsed ?? "").trim());
  const perDayWeatherModeCounts = countBy(perDayTrace, (row) => String(row.weatherModeUsed ?? "").trim());
  const perDayClassificationCounts = countBy(perDayTrace, (row) => String(row.dayClassification ?? "").trim());
  const keepRefUtcDateKeyCount = lockboxExecutionSummary.keepRefUtcDateKeyCount;
  const dailySourceClassificationsSummary = asRecord(tuningSummary.dailySourceClassificationsSummary);
  const monthlyLayer = monthlyLayerSummary(modeInfo.modeFamily);

  const inputGroups: CalculationLogicInputGroup[] = [
    {
      key: "source-actual-intervals",
      label: "Source actual intervals",
      used: modeInfo.modeFamily !== "profile_only",
      sourceOfTruth:
        sourceHouseId != null
          ? `Persisted source-house interval identity (${String(sourceTruthContext.intervalSourceIdentity ?? "identity not attached")})`
          : "Not attached",
      role:
        modeInfo.modeFamily === "actual_backed"
          ? "Main baseline truth"
          : "Trusted reference pool and source-derived seed context",
      priorityBand: modeInfo.modeFamily === "profile_only" ? "Not Used" : modeInfo.modeFamily === "actual_backed" ? "Reference Truth Pool" : "Primary Driver",
      details: [
        `Trusted fingerprint days: ${formatMaybeCount(fingerprintDiagnostics.trustedIntervalFingerprintDayCount)}`,
        `Interval fingerprint: ${String(sourceTruthContext.intervalSourceIdentity ?? "not attached")}`,
      ],
    },
    {
      key: "manual-monthly",
      label: "Manual monthly totals",
      used: modeInfo.modeFamily === "manual_monthly",
      sourceOfTruth:
        modeInfo.modeFamily === "manual_monthly"
          ? "Shared manual Stage 1 helper -> lockbox monthly constraints"
          : "Not used by this mode",
      role: modeInfo.modeFamily === "manual_monthly" ? "Fixed monthly constraint" : "Inactive",
      priorityBand: modeInfo.modeFamily === "manual_monthly" ? "Hard Constraint" : "Not Used",
      details: [
        monthlyDiagnostics.length > 0
          ? `Monthly target diagnostics attached for ${monthlyDiagnostics.length} month(s)`
          : "No monthly target diagnostics attached",
        modeInfo.modeFamily === "manual_monthly"
          ? "Bill-range semantics stay relevant for reconciliation."
          : "No monthly bill-range constraint path is active.",
      ],
    },
    {
      key: "manual-annual",
      label: "Manual annual total",
      used: modeInfo.modeFamily === "manual_annual",
      sourceOfTruth:
        modeInfo.modeFamily === "manual_annual"
          ? `Shared annual constraint (${formatMaybeNumber(sourceContext.sourceDerivedAnnualTotalKwh, 0)} kWh when attached)`
          : "Not used by this mode",
      role: modeInfo.modeFamily === "manual_annual" ? "Fixed annual constraint" : "Inactive",
      priorityBand: modeInfo.modeFamily === "manual_annual" ? "Hard Constraint" : "Not Used",
      details: [
        modeInfo.modeFamily === "manual_annual"
          ? "Annual total is preserved while monthly/daily shape is derived later."
          : "No annual constraint path is active.",
      ],
    },
    {
      key: "home-profile",
      label: "Home profile",
      used: profileContext.profileHouseId != null || modeInfo.modeFamily === "profile_only",
      sourceOfTruth: `Profile house ${String(profileContext.profileHouseId ?? testHomeId ?? "not attached")}`,
      role: modeInfo.modeFamily === "profile_only" ? "Primary synthetic driver" : "Context and tuning prior",
      priorityBand: modeInfo.modeFamily === "profile_only" ? "Primary Driver" : "Secondary Driver",
      details: [
        `Home profile snapshot ref: ${String(profileContext.homeProfileSnapshotRef ?? "not attached")}`,
      ],
    },
    {
      key: "appliance-profile",
      label: "Appliance profile",
      used: profileContext.profileHouseId != null || modeInfo.modeFamily === "profile_only",
      sourceOfTruth: `Profile house ${String(profileContext.profileHouseId ?? testHomeId ?? "not attached")}`,
      role: modeInfo.modeFamily === "profile_only" ? "Primary synthetic driver" : "Context and tuning prior",
      priorityBand: modeInfo.modeFamily === "profile_only" ? "Primary Driver" : "Secondary Driver",
      details: [
        `Appliance profile snapshot ref: ${String(profileContext.applianceProfileSnapshotRef ?? "not attached")}`,
      ],
    },
    {
      key: "weather",
      label: "Weather inputs",
      used: Boolean(identityContext.weatherLogicMode ?? sourceContext.weatherIdentity ?? meta.weatherSourceSummary),
      sourceOfTruth: joinNonEmpty([
        String(identityContext.weatherLogicMode ?? sourceContext.weatherLogicMode ?? "weather mode not attached"),
        String(sourceTruthContext.weatherDatasetIdentity ?? sourceContext.weatherIdentity ?? "weather identity not attached"),
        String(sourceTruthContext.weatherSourceIdentity ?? meta.weatherSourceSummary ?? "weather provenance not attached"),
      ]),
      role: "Daily-total adjustment and weather-regime shape selection",
      priorityBand: "Conditional Adjustment",
      details: [
        `Weather mode counts: ${describeCountMap(perDayWeatherModeCounts)}`,
        `Weather classifications: ${describeCountMap(perDayClassificationCounts)}`,
      ],
    },
    {
      key: "travel-validation",
      label: "Travel/vacant and validation selection",
      used: travelRangeList.length > 0 || validationKeyList.length > 0 || keepRefUtcDateKeyCount != null,
      sourceOfTruth: "Persisted lockbox travel ranges and validation keys",
      role: "Exclusion and compare-scope control",
      priorityBand: "Exclusion",
      details: [
        `Travel ranges: ${travelRangeList.length}`,
        `Validation/test days: ${validationKeyList.length}`,
        `Modeled keep-ref days: ${formatMaybeCount(keepRefUtcDateKeyCount)}`,
      ],
    },
    {
      key: "usage-shape-profile",
      label: "Usage shape profile",
      used: Boolean(sourceTruthContext.intervalUsageFingerprintIdentity ?? profileContext.usageShapeProfileIdentity),
      sourceOfTruth: String(
        sourceTruthContext.intervalUsageFingerprintIdentity ??
          profileContext.usageShapeProfileIdentity ??
          "not attached"
      ),
      role: "Interval-shape bucket selection and fallback shape context",
      priorityBand: modeInfo.modeFamily === "actual_backed" ? "Secondary Driver" : "Primary Driver",
      details: [
        `Shape variants observed: ${describeCountMap(perDayShapeVariantCounts)}`,
        `Month/day-type buckets: ${describeCountMap({
          months: asArray<string>(fingerprintDiagnostics.fingerprintMonthBucketsUsed).length,
          weekdayWeekend: asArray<string>(fingerprintDiagnostics.fingerprintWeekdayWeekendBucketsUsed).length,
          weather: asArray<string>(fingerprintDiagnostics.fingerprintWeatherBucketsUsed).length,
        })}`,
      ],
    },
    {
      key: "fallback-estimate",
      label: "Fallback estimation path",
      used: modeInfo.modeFamily !== "actual_backed",
      sourceOfTruth: "Shared simulator fallback ladder",
      role: "Used only when stronger monthly/day-shape evidence is missing",
      priorityBand: modeInfo.modeFamily === "actual_backed" ? "Not Used" : "Fallback",
      details: [
        `Observed daily fallback levels: ${describeCountMap(perDayFallbackCounts)}`,
      ],
    },
  ];

  const layers: CalculationLogicLayer[] = [
    {
      key: "input-constraint-layer",
      title: "1. Input / Constraint Layer",
      summary: modeInfo.stageOnePath,
      variablesUsed: inputGroups.filter((group) => group.used).map((group) => group.label),
      preservedOrLocked:
        modeInfo.modeFamily === "actual_backed"
          ? ["Source interval truth", "Validation/test selection only changes grading scope"]
          : monthlyLayer.preservedOrLocked,
      simulatedOrDerived:
        modeInfo.modeFamily === "actual_backed"
          ? ["Modeled keep-ref/test outputs only where the shared producer requires them"]
          : monthlyLayer.simulatedOrDerived,
      fallbackOrder: [],
      modeSpecificRules: [
        modeInfo.modeOverview,
        `Selected mode key: ${selectedMode || lockboxMode || "not attached"}`,
      ],
    },
    {
      key: "monthly-target-layer",
      title: "2. Monthly Target Layer",
      summary: monthlyLayer.summary,
      variablesUsed: [
        "Monthly or annual constraint inputs",
        "Source-derived monthly/annual diagnostics",
        "Profile priors when stronger evidence is missing",
      ],
      preservedOrLocked: monthlyLayer.preservedOrLocked,
      simulatedOrDerived: monthlyLayer.simulatedOrDerived,
      fallbackOrder:
        modeInfo.modeFamily === "manual_monthly"
          ? [
              "Shared monthly payload precedence first",
              "Actual-derived seeded statement ranges when usable source monthly payload is missing",
              "Stage 2 still uses the shared producer path after normalization",
            ]
          : modeInfo.modeFamily === "manual_annual"
            ? [
                "Shared annual payload precedence first",
                "Actual-derived annual seed when a usable annual payload is missing",
                "No monthly bill-range reconciliation is injected into annual mode",
              ]
            : modeInfo.modeFamily === "profile_only"
              ? ["Profile-only priors lead because no stronger source truth is attached"]
              : ["Actual interval aggregation defines the monthly baseline when interval truth is available"],
      modeSpecificRules: monthlyLayer.modeSpecificRules,
    },
    {
      key: "reference-pool-layer",
      title: "3. Trusted Reference Pool Layer",
      summary: "Trusted interval days build the reference pool and fingerprint context; exclusions remove low-trust days before daily and shape selection.",
      variablesUsed: [
        "Trusted interval fingerprint days",
        "Travel/vacant exclusions",
        "Incomplete meter / leading missing exclusions",
        "Validation keep-ref settings",
      ],
      preservedOrLocked: ["Trusted source-day evidence that remains in the fingerprint pool"],
      simulatedOrDerived: ["Modeled keep-ref outputs for selected validation/test days when applicable"],
      fallbackOrder: [
        `Trusted days: ${formatMaybeCount(fingerprintDiagnostics.trustedIntervalFingerprintDayCount)}`,
        `Travel/vacant excluded: ${formatMaybeCount(fingerprintDiagnostics.excludedTravelVacantFingerprintDayCount)}`,
        `Incomplete meter excluded: ${formatMaybeCount(fingerprintDiagnostics.excludedIncompleteMeterFingerprintDayCount)}`,
        `Leading missing excluded: ${formatMaybeCount(fingerprintDiagnostics.excludedLeadingMissingFingerprintDayCount)}`,
      ],
      modeSpecificRules: [
        keepRefUtcDateKeyCount != null
          ? `Validation keep-ref UTC day count: ${formatMaybeCount(keepRefUtcDateKeyCount)}`
          : "No modeled keep-ref count was attached to this artifact.",
      ],
    },
    {
      key: "daily-total-layer",
      title: "4. Daily Total Selection Layer",
      summary:
        "The shared day selector chooses a target daily kWh from the strongest available same-shape history, then falls back step-by-step when that evidence is weak.",
      variablesUsed: [
        "Month/day-type history",
        "Neighbor day-of-month samples",
        "Adjacent-month day-type averages",
        "Global fallback averages",
      ],
      preservedOrLocked: ["Hard monthly or annual constraints remain intact above this layer"],
      simulatedOrDerived: ["Per-day kWh targets"],
      fallbackOrder: [
        "Same-month nearest day-of-month neighbor",
        "Same-month weekday/weekend average",
        "Adjacent-month weekday/weekend average",
        "Same-month overall average",
        "Season overall average",
        "Global weekday/weekend average",
        "Global overall average",
      ],
      modeSpecificRules: [
        `Observed fallback levels in this artifact: ${describeCountMap(perDayFallbackCounts)}`,
      ],
    },
    {
      key: "weather-layer",
      title: "5. Weather Adjustment Layer",
      summary:
        "Weather adjusts the selected day total after the base day is chosen. Heating/cooling days can scale the target, and event days can add stronger freeze or aux-heat behavior.",
      variablesUsed: ["Weather logic mode", "Weather identity/provenance", "Day classification", "Weather severity multiplier"],
      preservedOrLocked: ["Base day total remains the anchor for normal days"],
      simulatedOrDerived: ["Weather-scaled day totals", "Event-day adders and classifications"],
      fallbackOrder: [
        "Normal day: keep base day total",
        "Weather-scaled day: blend weather-adjusted total back toward the profile anchor",
        "Extreme cold / freeze-protect day: use full event energy",
      ],
      modeSpecificRules: [
        `Weather provenance: ${String(sourceTruthContext.weatherSourceIdentity ?? meta.weatherSourceSummary ?? "not attached")}`,
        `Weather mode/classification counts: ${describeCountMap({ ...perDayWeatherModeCounts, ...perDayClassificationCounts })}`,
      ],
    },
    {
      key: "shape-layer",
      title: "6. Interval Shape Layer",
      summary:
        "Once the day total is set, the shared shape selector chooses the strongest available 96-slot profile for that month/day-type/weather regime combination.",
      variablesUsed: ["Usage shape profile identity", "Month/day-type/weather buckets", "Per-day shape variant selection"],
      preservedOrLocked: ["Daily total chosen in the previous layer"],
      simulatedOrDerived: ["96-slot interval shape", "Per-interval kWh allocation"],
      fallbackOrder: [
        "Month + day-type + weather regime",
        "Month + day-type",
        "Month flat shape",
        "Weekday/weekend + weather regime",
        "Weekday/weekend flat shape",
        "Uniform 96-slot fallback",
      ],
      modeSpecificRules: [
        `Observed shape variants: ${describeCountMap(perDayShapeVariantCounts)}`,
      ],
    },
    {
      key: "stitch-layer",
      title: "7. Stitch / Final Output Layer",
      summary:
        "The shared producer writes the final daily, monthly, interval, and artifact metadata once the lockbox run completes; GapFill only reads that persisted truth.",
      variablesUsed: ["Shared producer path flag", "Artifact input hash", "Full chain hash", "Projection read mode"],
      preservedOrLocked: ["Shared Stage 2 producer path"],
      simulatedOrDerived: ["Persisted baseline projection and display rows"],
      fallbackOrder: [],
      modeSpecificRules: [
        `Shared producer path used: ${sharedProducerPathUsed ? "true" : "false"}`,
        `Artifact input hash: ${String(lockboxExecutionSummary.artifactInputHash ?? "not attached")}`,
        `Read mode / projection mode: ${joinNonEmpty([
          String(projectionReadSummary.readMode ?? ""),
          String(projectionReadSummary.projectionMode ?? ""),
        ]) || "not attached"}`,
      ],
    },
    {
      key: "compare-layer",
      title: "8. Compare / Scoring Layer",
      summary:
        "GapFill scoring stays read-only and artifact-backed. Persisted validation/test compare rows and metrics are read after the shared producer finishes; no route-local simulator path is introduced.",
      variablesUsed: ["Validation/test keys", "Persisted compare rows", "Persisted compare metrics", "Diagnostics verdict"],
      preservedOrLocked: ["Compare/scoring semantics"],
      simulatedOrDerived: ["Error metrics and row-level deltas"],
      fallbackOrder: [],
      modeSpecificRules: [
        `Persisted compare rows: ${formatMaybeCount(
          projectionReadSummary.validationRowsCount ?? compareRows.length
        )}`,
        `WAPE: ${formatMaybeNumber(compareMetrics.wape)} | MAE: ${formatMaybeNumber(compareMetrics.mae)}`,
      ],
    },
  ];

  const priorityItems: CalculationLogicPriorityItem[] = [
    ...(modeInfo.modeFamily === "manual_monthly"
      ? [
          {
            label: "Monthly totals",
            priorityBand: "Hard Constraint" as const,
            explanation: "Monthly totals are preserved while daily and interval detail is generated underneath them.",
          },
          {
            label: "Bill-range semantics",
            priorityBand: "Primary Driver" as const,
            explanation: "Statement-range context matters for reconciliation and monthly target interpretation.",
          },
        ]
      : []),
    ...(modeInfo.modeFamily === "manual_annual"
      ? [
          {
            label: "Annual total",
            priorityBand: "Hard Constraint" as const,
            explanation: "The annual kWh total is fixed first, then monthly and daily allocation are derived.",
          },
        ]
      : []),
    ...(modeInfo.modeFamily === "actual_backed"
      ? [
          {
            label: "Actual interval pool",
            priorityBand: "Reference Truth Pool" as const,
            explanation: "Trusted source intervals lead the run and define the baseline evidence pool.",
          },
        ]
      : []),
    {
      label: "Trusted reference-pool quality",
      priorityBand: "Primary Driver",
      explanation:
        "The number and cleanliness of trusted fingerprint days materially affects daily and shape selection quality.",
    },
    {
      label: "Weather logic",
      priorityBand: "Conditional Adjustment",
      explanation: "Weather changes daily totals after the base day is selected and can alter the weather-regime shape bucket.",
    },
    {
      label: "Usage shape profile",
      priorityBand: modeInfo.modeFamily === "actual_backed" ? "Secondary Driver" : "Primary Driver",
      explanation: "Shape buckets determine how the final daily total is spread across 96 intervals.",
    },
    {
      label: "Fallback path frequency",
      priorityBand: "Fallback",
      explanation: "More fallback usage means weaker same-month/day-type evidence was available for this run.",
    },
  ];

  const exclusions: CalculationLogicExclusionItem[] = [
    {
      label: "Travel/vacant ranges",
      value: travelRangeList.length > 0 ? `${travelRangeList.length} range(s)` : "none attached",
      effect: "Removed from the trusted pool and modeled through the shared simulator instead of treated as clean reference truth.",
    },
    {
      label: "Incomplete meter days",
      value: formatMaybeCount(fingerprintDiagnostics.excludedIncompleteMeterFingerprintDayCount),
      effect: "Excluded from fingerprint/reference-pool truth so bad meter coverage does not anchor the simulation.",
    },
    {
      label: "Leading missing days",
      value: formatMaybeCount(fingerprintDiagnostics.excludedLeadingMissingFingerprintDayCount),
      effect: "Excluded from trusted reference truth and later filled by the shared simulator path.",
    },
    {
      label: "Validation/test modeled keep-ref logic",
      value: formatMaybeCount(keepRefUtcDateKeyCount),
      effect: "Selected validation/test days can remain in the reference pool while still producing modeled outputs for compare.",
    },
    {
      label: "Observed simulated-reason codes",
      value: describeCountMap(perDayReasonCounts),
      effect: "Shows which day classes were modeled rather than passed straight through from trusted meter truth.",
    },
    {
      label: "Daily source classifications",
      value: describeCountMap(
        Object.fromEntries(
          Object.entries(dailySourceClassificationsSummary).map(([key, value]) => [key, Number(value) || 0])
        )
      ),
      effect: "Explains which source categories dominated the final stitched daily output.",
    },
  ];

  const tuningLevers: CalculationLogicTuningLever[] = [
    ...(modeInfo.modeFamily === "manual_monthly"
      ? [
          {
            label: "Monthly constraint quality",
            priorityBand: "Hard Constraint" as const,
            explanation: "If the monthly totals or seeded statement ranges are off, every downstream daily/interval result is anchored to the wrong monthly target.",
          },
        ]
      : []),
    ...(modeInfo.modeFamily === "manual_annual"
      ? [
          {
            label: "Annual seed quality",
            priorityBand: "Hard Constraint" as const,
            explanation: "The annual total is the top-level anchor; downstream month/day tuning cannot fix a wrong annual input.",
          },
        ]
      : []),
    ...(modeInfo.modeFamily === "actual_backed"
      ? [
          {
            label: "Reference-pool cleanliness",
            priorityBand: "Reference Truth Pool" as const,
            explanation: "Travel, incomplete meter, and leading-missing exclusions materially change how much trusted actual history remains available.",
          },
        ]
      : []),
    {
      label: "Validation/test-day composition",
      priorityBand: "Primary Driver",
      explanation: "Changing the selected validation days changes what gets scored and which keep-ref behaviors are exercised.",
    },
    {
      label: "Weather scaling behavior",
      priorityBand: "Conditional Adjustment",
      explanation: "Heating/cooling regime changes and event-day caps alter daily kWh before interval shape is applied.",
    },
    {
      label: "Shape bucket quality",
      priorityBand: "Primary Driver",
      explanation: "Better month/day-type/weather buckets reduce reliance on flatter fallback shapes and usually move interval-error metrics the most.",
    },
    {
      label: "Fallback frequency",
      priorityBand: "Fallback",
      explanation: "When more days fall through to adjacent/global fallbacks, the run is relying more on broad priors and less on strong local evidence.",
    },
  ];

  return {
    selectedMode: selectedMode || lockboxMode || "not attached",
    modeLabel: modeInfo.modeLabel,
    modeFamily: modeInfo.modeFamily,
    modeOverview: modeInfo.modeOverview,
    stageOnePath: modeInfo.stageOnePath,
    stageTwoPath:
      "Shared lockbox -> shared Past producer -> persisted artifact -> read-only GapFill compare/diagnostics view.",
    sharedProducerPathUsed,
    sourceHouseId,
    testHomeId,
    inputGroups,
    layers,
    priorityItems,
    exclusions,
    tuningLevers,
    rawDiagnostics: {
      identityContext,
      sourceTruthContext,
      lockboxExecutionSummary,
      projectionReadSummary,
      tuningSummary,
      lockboxInput,
      perRunTrace,
      compareMetrics,
    },
  };
}
