export enum IntervalSeriesKind {
  ACTUAL_USAGE_INTERVALS = "ACTUAL_USAGE_INTERVALS",
  BASELINE_INTERVALS = "BASELINE_INTERVALS",
  PAST_SIM_BASELINE = "PAST_SIM_BASELINE",
  FUTURE_SIM_BASELINE = "FUTURE_SIM_BASELINE",
  FUTURE_SIM_USAGE = "FUTURE_SIM_USAGE",
}

